# Generated by Django 3.2.4 on 2021-07-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokefriend', '0003_alter_trainer_last_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['-last_modified']},
        ),
        migrations.AlterField(
            model_name='trainer',
            name='code',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='team',
            field=models.CharField(choices=[('ANY', 'Any'), ('MYSTIC', 'Mystic'), ('VALOR', 'Valor'), ('INSTINCT', 'Instinct')], default='ANY', max_length=10),
        ),
    ]
